baseURL = "https://madhurb.xyz"
languageCode = "en-us"
title = "Madhur Biyani"
theme = "minimal"


[params]
    author = "Nikita Voloboev"
    description = "Loves [making](https://nikitavoloboev.xyz/projects/) and [sharing](https://wiki.nikitavoloboev.xyz/sharing) things. <br/>Building [Learn Anything](https://learn-anything.xyz/) and [tools](https://wiki.nikitavoloboev.xyz/sharing/my-github)."
    copyright = " "
    accent = "#E34E47"
    showBorder = true
    backgroundColor = ""
    font = "Quicksand" # should match the name on Google Fonts!

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "https://medium.com/@nikitavoloboev"
    name = "Blog"
    weight = 4

[[menu.main]]
    url = "https://wiki.nikitavoloboev.xyz"
    name = "Wiki"
    weight = 5

[[menu.main]]
    url = "https://github.com/nikitavoloboev/ama#readme"
    name = "AMA"
    weight = 8

[[menu.main]]
    url = "/cv.pdf"
    name = "CV"
    weight = 9

[[menu.main]]
    url = "https://github.com/sponsors/nikitavoloboev"
    name = "♥"
    weight = 10

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/
[[menu.icon]]
    url = "https://twitter.com/nikitavoloboev"
    name = "twitter"
    weight = 1

[[menu.icon]]
    url = "https://github.com/nikitavoloboev"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://www.instagram.com/nikitavoloboev"
    name = "instagram"
    weight = 3

[[menu.icon]]
    url = "https://open.spotify.com/user/nikitavoloboev"
    name = "spotify"
    weight = 4

[[menu.icon]]
    url = "https://www.youtube.com/channel/UCEKqrUfr_FMKIO9XSJS4vDw"
    name = "youtube"
    weight = 5

[[menu.icon]]
    url = "https://t.me/joinchat/BBKnQU4_rty6_942PFbPbw"
    name = "telegram"
    weight = 6

[[menu.icon]]
    url = "mailto:nikita.voloboev@gmail.com"
    name = "envelope-o"
    weight = 7
